use fp20
select * from dbo.['Fuel_Prices_Argentina_2016-2023$']

--What is the average price of Gasoil Grade 2 across all provinces?
select Province, [Product Type], round(avg([Price]),2) 'Average Price'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where [Product Type] = 'Gasoil Grade 2'
group by Province, [Product Type]
order by 'Average Price' desc

--Which company has the highest total sales by city?
select [Company Name], sum([Price ]) 'Total Sales'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
group by [Company Name]
order by 'Total Sales' desc

select * from dbo.['Fuel_Prices_Argentina_2016-2023$']

--How is the average price of Petrol Premium - 95 Octane from September 2022 to October 2023?
select [Year_Month ID], [Product Type], round(avg(Price),2) 'Average Price'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where [Product Type] = 'Petrol Premium - 95 Octane' and [Year_Month ID] between '2022-09' and '2023-10'
group by [Year_Month ID], [Product Type]
order by [Year_Month ID]

--Which region has the highest average price for Compressed Natural Gas?
select Region, round(avg([Price ]), 2) 'Average Price'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where [Product Type] = 'Compressed Natural Gas'
group by Region
order by 'Average Price' desc

--Can we observe any significant difference in fuel prices between daytime and nighttime shifts?
select [Shift Type], round(avg(Price),2) 'average price'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
group by [Shift Type]

select * from dbo.['Fuel_Prices_Argentina_2016-2023$']

--What is the price range for Petrol unleaded - 95/98 Octane in the Buenos Aires province?
select Province, [Product Type], max([Price ]) - min([Price ]) 'Range'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where Province = 'Buenos Aires' and [Product Type] = 'Petrol unleaded - 95/98 Octane'
group by Province, [Product Type]
order by 'Range' desc


--How many different types of products are sold by the company "AUTOMOVIL CLUB ARGENTINO"?
select [Product Type], [Company Name], count([Product Type]) 'count'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where [Company Name] = 'AUTOMOVIL CLUB ARGENTINO'
group by [Product Type], [Company Name]
order by 'count' desc

select * from dbo.['Fuel_Prices_Argentina_2016-2023$']

--Which city in the Patagonia region has the highest recorded price for any fuel type?
select Region, [Product Type], round(sum(Price),2) 'Sales Price'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where Region = 'Patagonia'
group by Region, [Product Type]
order by 'Sales Price' desc

--What are the top 10 companies by sales revenue in 2023? 
select TOP 10 [Company ID ], [Company Name], round(sum(Price),2) 'Sales Revenue'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where year(Date) = '2023'
group by [Company ID ], [Company Name]
order by 'Sales Revenue' desc

--What is the total revenue generated by each flagged company if we assume each price corresponds to one sale?
select [Flag Company], round(sum(Price),2) 'Total Revenue'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
group by [Flag Company]
order by 'Total Revenue' desc

select * from dbo.['Fuel_Prices_Argentina_2016-2023$']

--Which company experienced the greatest percentage change in the price of Gasoil Grade 3 between September 2022 and October 2023?
with CTE_1 AS (
select [Company ID ], [Company Name], [Product Type], 
round(price/(sum(Price) over(partition by [Company Name]))*100,2) 'Percent Change'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where [Product Type] = 'Gasoil Grade 3'and [Year_Month ID] between '2022-09' and '2023-10'
)
select top 1* from CTE_1
order by 'Percent Change' desc

--What was the highest and lowest prices of Gasoil Grade 2 in the province of Buenos Aires during the year 2023?
select Province, [Product Type], max(Price) 'Maximum', min(Price) 'Minimum'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where [Product Type] = 'Gasoil Grade 2'and year(Date) = '2023'
group by Province, [Product Type]

--Which month had the greatest profit win in the prices of Petrol unleaded - 95/98 Octane during the year 2022?
select [Year_Month ID], [Product Type], round(sum(Price),2) 'Profit'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where [Product Type] = 'Petrol unleaded - 95/98 Octane'and year(Date) = '2022'
group by [Year_Month ID], [Product Type]
order by 'Profit' desc

select * from dbo.['Fuel_Prices_Argentina_2016-2023$']

--Are there significant correlations between geographical location (latitude and longitude) and product prices for a specific company?
select Latitude, Longitude, [Company Name], avg(Price) 'Average Price'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where Latitude is not null and  Longitude is not null
group by Latitude, Longitude, [Company Name]

--What was the product that showed the highest sales?
select [Product Type], round(sum(price),2) 'Total Sales'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
group by [Product Type]
order by 'Total Sales' desc

--Was there any month in the year 2023 where a trend of increasing prices for all products sold by a specific company was observed?
select Date, [Company Name], [Product Type], round(avg(Price),2) 'Average Price'
from dbo.['Fuel_Prices_Argentina_2016-2023$']
--where year(Date) = '2023' and [Company Name] = 'AUTOMOVIL CLUB ARGENTINO'
where year(Date) = '2023' 
group by Date, [Company Name], [Product Type]
order by Date

--Which company showed the greatest volatility in the prices of all its products during the year 2023?
select [Company Name], isnull(round(VAR(Price),2),0) as Variance
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where year(Date) = '2023' 
group by [Company Name]
order by Variance desc

--OR ALTERNATIVELY
with Volatility as (
select [Company Name], isnull(round(VAR(Price),2),0) as Variance
from dbo.['Fuel_Prices_Argentina_2016-2023$']
where year(Date) = '2023' 
group by [Company Name]
)
select top 1 [Company Name], Variance from Volatility
order by Variance desc